name: Gradle Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vm-jobs:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: petclinic-heroku
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Test Database Structure
        run: ./gradlew -q createIntegrationtestDb
        env:
          # DATABASE_* ENV variables are used for the gradle task 'createIntegrationtestDb' - which sets up the test database
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_DB_NAME: petclinic-heroku-test
          DATABASE_HOST: localhost
          DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}


      - name: Run Integrationtests
        run: ./gradlew -q test
        env:
          # JDBC_DATASOURCE_URL is used for the execution of gradle task 'test'.
          # The application uses this ENV variable for the 'integrationtest' spring profile (see integrationtest-app.properties)
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/petclinic-heroku-test?user=postgres&password=postgres

          # DATABASE_* ENV variables are used for the gradle task 'createIntegrationtestDb' - which sets up the test database
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_DB_NAME: petclinic-heroku-test
          DATABASE_HOST: localhost
          DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
